networks:
  arium_network:
    driver: bridge
services:
  app:
    networks:
      - arium_network
    build:
      context: ../..
      dockerfile: devops/docker/Dockerfile

    image: arium-react:latest
    container_name: arium-react
    restart: unless-stopped

    ports:
      - "3000:4173"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/arium

  mongo:
    networks:
      - arium_network
    image: mongo:latest
    container_name: arium-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=arium

volumes:
  mongo_data:
